# Generated by Django 5.1.15 on 2026-07-22 13:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('accessed_by', models.CharField(help_text='Username or service identifier of the accessor', max_length=255)),
                ('action', models.CharField(choices=[('read', 'Read'), ('write', 'Write'), ('export', 'Export'), ('delete', 'Delete')], max_length=20)),
                ('resource_type', models.CharField(help_text='e.g., EnvironmentScan, AnonymizationMapping', max_length=100)),
                ('resource_id', models.CharField(max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('details', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Access Log',
                'verbose_name_plural': 'Access Logs',
                'db_table': 'access_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnonymizationMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('anonymized_id', models.UUIDField(default=uuid.uuid4, help_text='The anonymized UUID used in research datasets', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='anonymization_mapping', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Anonymization Mapping',
                'verbose_name_plural': 'Anonymization Mappings',
                'db_table': 'anonymization_mappings',
                'permissions': [('view_mapping_data', 'Can view anonymization mapping data')],
            },
        ),
        migrations.CreateModel(
            name='AnonymizedScan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('anonymized_user_id', models.UUIDField(db_index=True, help_text='One-way anonymized identifier (not reversible without mapping table)')),
                ('scan_data', models.JSONField(default=dict, help_text='LLM output and scores with PII removed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exported_at', models.DateTimeField(blank=True, null=True)),
                ('dataset_batch', models.CharField(blank=True, help_text='Identifier for the research dataset batch this was exported in', max_length=100)),
                ('original_scan', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anonymized_version', to='core.environmentscan')),
            ],
            options={
                'verbose_name': 'Anonymized Scan',
                'verbose_name_plural': 'Anonymized Scans',
                'db_table': 'anonymized_scans',
            },
        ),
        migrations.CreateModel(
            name='RoyaltyLedger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dataset_batch', models.CharField(max_length=100)),
                ('scans_contributed', models.PositiveIntegerField(default=0)),
                ('royalty_amount_cents', models.PositiveIntegerField(default=0, help_text='Royalty amount in cents (USD)')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('stripe_transfer_id', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='royalty_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Royalty Ledger Entry',
                'verbose_name_plural': 'Royalty Ledger',
                'db_table': 'royalty_ledger',
                'ordering': ['-created_at'],
            },
        ),
    ]
